tinypcminfo: make function pcm_get_format_name() static
When building tinyalsa with gcc 5.x, the following warnings appear:

tinypcminfo.c:97:52: warning: 'format_lookup' is static but used in inline function 'pcm_get_format_name' which is not static
     return bit_index < ARRAY_SIZE(format_lookup) ? format_lookup[bit_index] : NULL;
                                                    ^
tinypcminfo.c:97:35: warning: 'format_lookup' is static but used in inline function 'pcm_get_format_name' which is not static
     return bit_index < ARRAY_SIZE(format_lookup) ? format_lookup[bit_index] : NULL;

And the build fails with:

tinypcminfo.o: In function `main':
tinypcminfo.c:(.text+0x2f0): undefined reference to `pcm_get_format_name'
collect2: error: ld returned 1 exit status

To fix this, this patch marks the pcm_get_format_name() as static,
since it's anyway only used in tinypcminfo.c.

Change-Id: I1f6a625a6b5cc9fe1a26ae0586c3c9ba0b69ad1a
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>